### ISSUE TITLE
Attributes not appearing in Appearance dropdown list

### ISSUE THREAD

**Issue by swainjo** [gephi/gephi#1319]
Steps to replicate:

Open attached file.
Go to Appearance tab
Select Node Size 
Drop Down list of Attributes
Pagerank is not listed
Go to Data Laboratory
Select Configure Displayed Columns
Check Pagerank is in data

This works fine on previous versions.

[COP21Nov29Nov30gInDeg1weak.graphml.zip](https://github.com/gephi/gephi/files/106206/COP21Nov29Nov30gInDeg1weak.graphml.zip)

**Comment by mbastian** [comment]
Have you updated Gephi (Help > Check for updates)? We released a hotfix for this bug, which will be included in the 0.9.1 version.

**Comment by rjurney** [comment]
Mat, I'm running master and this problem still exists. I just pulled latest, I still can't size by anything but degree.

**Comment by mbastian** [comment]
The problem here appears to be with the ranking vs partition detection. Columns that are wrongly detected as partition columns (such as pagerank here) aren't listed in size because you can only do ranking transformations with size. A workaround is to go to color and then select "Switch to Ranking". The column appears then in size as well. I'll see if I can improve the ranking vs partition detection though.
