### ISSUE TITLE
Graph is always over Data Table in macOS

### ISSUE THREAD

**Issue by juanmas07** [gephi/gephi#1647]
<img width="972" alt="screen shot 2017-01-02 at 4 42 53 pm" src="https://cloud.githubusercontent.com/assets/2141907/21595246/9630f980-d10a-11e6-8ef5-1f33fc86f04b.png">

The graph don't let me see the data table, it is always on top of it. 

* Version used: Gephi 0.9.1
* Operating System: OS X 10.11.6

**Comment by DaveL17** [comment]
Seeing the same behavior.  

Gephi: 0.9.1
OS X: 10.12.3

**Comment by mikethicke** [comment]
Happening for me as well. In fact when the graph is open it covers all tabs (Preview, Edit, etc.).

Gephi: 0.9.1
OS X: 10.12.4

**Comment by kyleboyle** [comment]
Any ideas on if this will get fixed? I can try to take a stab at it if someone can give me a few pointers where to look in the code. This issue makes using the application on macos somewhat unbearable.

**Comment by eduramiba** [comment]
This will be hopefully fixed with the new visualization engine, but it is still far from release.

**Comment by kyleboyle** [comment]
Ok, well in the meantime if anyone sees this bug, here is a diff for a kludge that makes the graph disappear when the Graph tab loses focus


```diff --git a/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/GraphTopComponent.java b/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/GraphTopComponent.java
index dc37e9c3d..be5394b78 100644
--- a/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/GraphTopComponent.java
+++ b/modules/VisualizationImpl/src/main/java/org/gephi/visualization/component/GraphTopComponent.java
@@ -290,11 +290,21 @@ public class GraphTopComponent extends TopComponent implements AWTEventListener
     @Override
     protected void componentActivated() {
         java.awt.Toolkit.getDefaultToolkit().addAWTEventListener(this, AWTEvent.KEY_EVENT_MASK);
+
+      if(engine != null) {
+        add(drawable.getGraphComponent(), BorderLayout.CENTER);
+        invalidate();
+      }
     }
 
     @Override
     protected void componentDeactivated() {
         java.awt.Toolkit.getDefaultToolkit().removeAWTEventListener(this);
+      if(engine != null) {
+        remove(drawable.getGraphComponent());
+        invalidate();
+      }
+
     }
```

**Comment by hopkira** [comment]
Still seeing the same problem Gephi 0.9.2 and Mac OSX 10.15.3

**Comment by mbastian** [comment]
Closing as we can't reproduce with the latest release. Please re-open if it's still happening with the 0.11 version.
