### ISSUE TITLE
Problem when saving (0.10.0)

### ISSUE THREAD

**Issue by grandjeanmartin** [gephi/gephi#2731]
## Current Behavior
When saving a .gephi file, the document seems to be saved (its number of kilobytes increases), but when you leave the project, the document loses its content (while still existing, but a few hundred bytes). When you open it again, it is an empty project.

## Your Environment

* Version used: Gephi 0.10.0
* Operating System: Mac OS Monterey 12.6

**Comment by MelitaThomas** [comment]
I have exactly the same issue. I have lost hours of work!  I have tried saving as gephi and as all files.

**Comment by jentsminger** [comment]
I am also encountering this issue. Issue is encountered with files held on both local device drive and on cloud storage drives. Also noticed a correlation (but not exclusively) of file "wipe" occurrence when clicking "save" upon failsafe prompt at program close. 

Never had this issue with Gephi 0.9.7. The new version appears to be unstable; as along with these file wipes, I'm also encountering program freezing. (File wipes occur with and without program freezes.) 

OS specs: Windows 11 Pro 64-bit, Version 22H2, Build 22621.1105 running on 16 GB RAM and a 12th Gen Intel i7. Error occurs even in high RAM availability state.

**Comment by ZackHaugan** [comment]
Same Issue here. Whenever I use the normal 'save' button, the .gephi file clearly increases in size when looking at the file from the file explorer view. However, whenever I go to close the file, It appears like no matter what you chose for the exit prompt, the file will decrease in size to 1kb and essentially become blank when opening it. 

This has only become an issue after updating Gephi to 0.10.0

OS: Windows 11 Home, Build 10.0.22621 with an Intel i7-1065G7 CPU and 16 GB of RAM.

**Comment by Duvuki** [comment]
I have same issue when saving to .gephi format.
OS ver: Ubuntu 20.04.5 LTS

**Comment by jentsminger** [comment]
UPDATE: This may be an issue with the 64-bit version of Gephi's latest release. When I ran the 32-bit version of Gephi 0.10.0, performance was more stable. 

> 
> OS specs: Windows 11 Pro 64-bit, Version 22H2, Build 22621.1105 running on 16 GB RAM and a 12th Gen Intel i7. Error occurs even in high RAM availability state.

**Comment by paulosrl** [comment]
I have same issue when saving to .gephi format. 
OS: Windows 11 22H2
Latest Java.

**Comment by mbastian** [comment]
Thanks for the report, the issue has been fixed. Please upgrade 0.10.1 (via Gephi > Check for Updates).

**Comment by bkotras13** [comment]
Hello,

I have the same problem (Windows 10, Gephi 0.10.1, 64x), and everything is up to date. How can I do ? 
Thanks
baptiste

**Comment by martyved** [comment]
I also have the same issue - Windows 10, Gephi 0.10.1, 64x. I had the issue on 0.10.0, and thought it was fixed on 0.10.1, but it still doesn't save any of my projects.

**Comment by inwonakng** [comment]
I also have an issue with version 0.10.1, OSX 14.1.1 (23B81). I opened the graph from a gexf file, but when I save the .gephi project and open it, the graph is not loaded.

**Comment by SamerAl-khateeb** [comment]
I am having a similar issue with Gephi 0.10.1 running on MacOS Sonoma v14.5 on the Apple M3 Max chip. When I try to save my graph, the app freezes and does not respond. I have to force quit it and restart. I see the file created, but if I try to open it, I encounter the same freeze issue! note that I updated Java to the latest version, i.e., Java 8 update 441 because I thought my older version of Java was causing the issue, but still the same. Any help?
